version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nickalie/go-calibre
    docker:
      - image: golang
    steps:
      - run: |
          sed -i "s/stretch main/stretch main contrib non-free/" /etc/apt/sources.list
          apt-get update
          apt-get install -y --no-install-recommends xz-utils unrar libgl1-mesa-glx qt5-default
      - run: wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
      - checkout
      - run: go get -t -v ./...
      - run: go test -v ./...
